version: '3.7'

services:
  app:
    build: 
      dockerfile: ./Dockerfile
    environment:
      - PORT=3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - 3030:3030
    networks:
      proxy-network:
        aliases:
          - app

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'fezinha'
      MYSQL_USER: 'fezinha'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"


networks:
  proxy-network:
    name: 'fezinha'
    driver: bridge
